### ISSUE TITLE
pardot form handler error (too many redirects)

### ISSUE THREAD

**Issue by emanuedh** [zaus/forms-3rdparty-integration#78] opened 2017-01-19 18:41 UTC
i am using 3rd party services plug in for wordpress to link contact form 7 forms to pardot via form handler. I have gotten the form handler to accept the information successfully when i am only mapping the email field in 3rd party services over to pardot (pardot form handler has more than one field mapped), but when I start trying to map multiple fields over in 3rd party services (using the correct id tags for both cf7 and pardot), i get the debugger message saying "array: too many redirects". what is the root of this issue and how do i solve it? 

Sample debugger error message below:

here was an error when trying to integrate with the 3rd party service {Pardot (NADA)} (http://www2.pearlsolutions.com/l/62072/2017-01-19/3cklld).

**FORM**
Title: NADA 2017 Landing Page Form
Intended Recipient: hillis@pearlsolutions.com
Source: http://pearlsolutions.staging.wpengine.com/nada2017/

**SUBMISSION**
Array
(
   [timeout] => 10
   [body] => Array
       (
           [email] => b@bu.com
           [first_name] => Bruce
           [last_name] => Thom
           [job_title] => GT
           [company] => bruce gt
           [Cell_Number] => 222 222 1111
       )

)

**RAW RESPONSE**
Array
(
   [safe_message] => error object
   [object] => WP_Error Object
       (
           [errors] => Array
               (
                   [http_request_failed] => Array
                       (
                           [0] => Too many redirects
                       )

               )

           [error_data] => Array
               (
               )

       )

)

**Comment by wmlsummers** [comment] 2017-02-26 19:17
I have the same issue but I cannot even connect just "email".  Were you able to fix this issue?  I would love the help.

**Comment by zaus** [comment] 2017-03-08 05:43
Duplicate of #73, but more detail here.

I can't reproduce as I don't have a Pardot to test against (or time, for that matter).  I think I commented more about this in the WP forum too...

**Comment by zaus** [comment] 2017-03-31 01:46
Also reported here:
https://wordpress.org/support/topic/form-being-submitted-multiple-times/
https://wordpress.org/support/topic/repeated-results-in-pardot/

**Comment by zaus** [comment] 2017-03-31 01:53
May be similar to #69?

**Comment by mawint** [comment] 2017-04-05 18:21
I was able to solve this with doing a normal cURL post instead of using wp_remote_post. 

Updated in forms-3rdparty-integration.php on about line 600. I know this breaks some of the applying of filters for the functions.php file though but in our case we weren't using them. 

I would love to see an update to the plugin that solves this problem. Here is what I updated the function with.

`$curl_opts = array(
				CURLOPT_URL => $service['url'].'/?'.http_build_query($post_args['body']),
				CURLOPT_CONNECTTIMEOUT => 5,
				CURLOPT_TIMEOUT => $post_args['timeout'],
				CURLOPT_POST => 1,
				//CURLOPT_PROTOCOLS => CURLPROTO_HTTPS,
				CURLOPT_SSL_VERIFYHOST => 2,
				CURLOPT_RETURNTRANSFER => 1
			);

			$ch = curl_init();
			curl_setopt_array($ch, $curl_opts);
			$response = curl_exec($ch);
			curl_close($ch);`

**Comment by zaus** [comment] 2017-05-11 15:41
I'm closing this as it sounds like weird WP/hosting issue rather than a problem with the plugin.

**Comment by zaus** [comment] 2017-05-11 15:41
I'm closing this as it sounds like weird WP/hosting issue rather than a problem with the plugin.

**Closed by zaus** 2017-05-11 15:41 UTC
Labels: duplicate, wontfix

**Comment by leendertvb** [comment] 2017-08-17 12:26
I managed to resolve this issue by matching all (required) fields in the 3rd-party-plugin with the fields as defined in the form handler of Pardot. If there is a mismatch, it will throw the error of “too many redirects”.

Hope this helps anyone.

**Comment by hirewebsolutions** [comment] 2018-07-16 10:09
Hello,

You can see bellow form integration with pardot add-ons:

Contact Form 7 - Pardot Integration: https://codecanyon.net/item/contact-form-7-pardot-integration/22240057

Gravity Forms - Pardot Integration: https://codecanyon.net/item/gravity-forms-pardot-integration/22240088

Ninja Forms - Pardot Integration: https://codecanyon.net/item/ninja-forms-pardot-integration/22241224

WPForms - Pardot Integration: https://codecanyon.net/item/wpforms-pardot-integration/22241369

Let us know if any concerns!
Thanks
