### ISSUE TITLE
No Longer Pushing Info to SF

### ISSUE THREAD

**Issue by Rondeau-CMM** [zaus/forms-3rdparty-integration#103] opened 2018-05-11 14:47 UTC
About 14 hours ago form submissions stopped being forwarded through to SalesForce where they are normally created as Leads. I know the Forms we're successfully submitted because I still received emails and I have Flamingo installed as a third back-up. I have the most current version of WP on my site and the most current version of your plug-in.

**Comment by Rondeau-CMM** [comment] 2018-05-11 17:54
**RAW RESPONSE**
Array
(
    [safe_message] => error object
    [object] => WP_Error Object
        (
            [errors] => Array
                (
                    [http_request_failed] => Array
                        (
                            [0] => cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
                        )

                )

            [error_data] => Array
                (
                )

        )

)

**Comment by zaus** [comment] 2018-05-15 16:34
I could also be mistaken - I just searched for your original error message and found this: https://forum.ait-pro.com/forums/topic/unable-to-upgrade-bps-pro-from-13-3-3-to-13-4/ so maybe increase the timeout setting in my plugin?

**Comment by Rondeau-CMM** [comment] 2018-05-15 17:27
I’ve made a lot of progress since I first reached out. I’ve ensured TLS 1.2 is enabled on my site and that Salesforce is accepting it. And, now I’ve increased the Request Timeout field to 120. I’m still receiving the same error.

I’m working with you, the folks that host my website and Salesforce sort of simultaneously. Is it possible yet that something needs to be done on the plug-in end, or that another plug-in is disrupting yours. I disabled my W3 Super Cache plug-in to see if that was creating any issues, but to no avail.

Thanks,
Adam

**Comment by zaus** [comment] 2018-05-17 00:58
It's possible, but I don't know what I would do as I'm using native wp functionality to make requests (`wp_remote_post`), so there shouldn't be anything for me to do.

I would suggest finding some other endpoint that can confirm you're actually sending TLS 1.2, like the suggestions at

**Comment by zaus** [comment] 2018-05-17 01:06
Sorry, did you have to switch to issue #105 because I closed this one?

**Comment by Rondeau-CMM** [comment] 2018-05-17 02:00
I didn't have to switch, I was just unsure if you checked closed issues. Thanks for reopening / continuing to look into this for me. I will continue the conversation on the new issue, as it has more complete information about my issue, so feel free to close this one.

**Comment by zaus** [comment] 2018-05-17 02:19
I think I still get notices from comments on closed issues, I only closed it because I didn't think it was specifically my plugin.

**Closed by zaus** 2018-05-17 02:19 UTC

**Comment by andru26** [comment] 2018-05-22 20:58
Hello Zaus,
I followed this topic and the one opened on wordpress.com and I have the same issue that other are describing. For more than a week CF7-3rdParty Integration plugin stopped sending leads to SF and I get the same "cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104" error. There is something wrong happening with the pugin and I couldn't find any confirmed solution by the people that reported it before.
I believe I speak for everyone when I say that we would really appreciate your help for a working fix for this error we are getting.

Many thanks!
