### ISSUE TITLE
Can't turn off debug mode

### ISSUE THREAD

**Issue by systatsoftware** [zaus/forms-3rdparty-integration#60] opened 2016-02-18 21:44 UTC
Despite unchecking the boxes for debug mode and all others, I still get debug emails each time a form is used. Also this error appears behind each check box:

 Warning: in_array() expects parameter 2 to be array, string given in /home/systat5/public_html/wp-content/plugins/forms-3rdparty-integration/forms-3rdparty-integration.php on line 393
 value='debug' />

Please advise. I'm using WordPress 4.4.2 running Esteem Pro theme.

- Greg

**Comment by zaus** [comment] 2016-02-19 04:45
Yeah, that's kind of serious.  I'll have to look into it this weekend.  Related to #55.

**Comment by zaus** [comment] 2016-02-25 09:36
Are you still having this problem with v1.6.6.3?  I thought I was also experiencing this issue but it turns out it was another plugin conflict instead.

**Comment by systatsoftware** [comment] 2016-02-25 18:35
I'm not sure. However, couple days ago I noticed the error messages nestled near the checkboxes are gone. I needed to get back to debug mode for some other work, when I'm done, I'll try turning off debug and advise when I can, Thanks for looking into this! Oh, which plugin did you find conflict with? We don't use a lot of them on our site but tell me which one and I'll check if we use that one.

**Comment by systatsoftware** [comment] 2016-02-26 16:53
I have turn off debug now and the problem still exists, please be advised.

The error messages next to the check boxes are still gone though....

**Comment by systatsoftware** [comment] 2016-03-09 17:33
Dear Zaus,

Just checking if you're still working this case as my inbox is stuffed everyday with error messages.
Also, as far as the success message 3rd Party is expecting to see from SalesForce, do you know what the message states and how to get 3rd Party to accept it as "a success"?

**Comment by systatsoftware** [comment] 2016-03-24 15:34
Dear Zaus,

Just checking again if you're still working this case as my inbox is stuffed everyday with error messages.

As far as the success message 3rd Party is expecting to see from SalesForce, do you know what the message states and how to get 3rd Party to accept it as "a success"?

**Comment by systatsoftware** [comment] 2016-03-31 18:40
Just making my weekly check in, issue still persists....

**Comment by zaus** [comment] 2016-04-01 08:42
Hey, sorry for not getting back to you.  The plugin problem I had was with another custom plugin I was in the middle of writing, so probably not applicable.

I really can't reproduce the problem -- disabling debug mode works 100% of the time on the several sites I've tried.  Can you enable `WP_DEBUG` mode (+ logging) to get more insight?

However, I'm thinking that maybe the problem isn't debug mode, but rather your second question regarding "error messages".  [Debug mode only applies to sending the debug message](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L632), but [anything considered an integration failure](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L571) (failure response, missing success clause, etc) will _always_ [send an email](https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/fplugin_base.php#L286).

Because you say
> * my inbox is stuffed everyday with error messages
> * As far as the success message 3rd Party is expecting to see from SalesForce, do you know what the message states and how to get 3rd Party to accept it as "a success"?

I'm thinking you've "misconfigured" the 'Success Condition'.  You only need to set it if you want the plugin to send you errors [when it can't find that value in the response](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L587); otherwise leave blank and it'll assume it succeeded (unless there was an [actual problem](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L572)).

Regarding what to expect from a successful response, usually something simple like "`success`" is all that's needed.  You should have lots of examples of 'successful' responses in your inbox (assuming Salesforce is getting the data correctly) -- the error email should include whatever the integration responded with, so just grab a piece of the repeated text.  If you want to paste an email here I can help you.

**Comment by zaus** [comment] 2016-04-01 08:43
I'm going to tentatively close it, assuming I was right.  We can continue the conversation here to figure out the 'success condition', but let me know if I need to reopen it as a bug.

**Closed by zaus** 2016-04-01 08:43 UTC
Labels: question

**Comment by zaus** [comment] 2016-04-01 08:47
For reference, this might be your problem -- https://wordpress.org/support/topic/cf7-3rdparty-integration-failure-salesforce-2

**Comment by systatsoftware** [comment] 2016-04-01 16:39
Ah, you mean the field called “Success Condition”; I’ve emptied out all those fields just now and have not seen any error messages arrive yet.

 

*fingers crossed* I’ll write you back if needed but I think this is fixed!

 

 

Hey, can I get your advise on some things?

 

On caching modules for WordPress, which one do you use? 

 

Also, we’re on a virtual server, should the domain have the gzip compression turned on? Some say use only WP caching only, what is your take?

 

Have a good weekend!

 

Best Regards,

 

Greg Barton

Marketing Assistant

Systat Software, Inc.

2107 North First Street Suite 360

San Jose, CA 95131

Tel: 408-715-7038 direct

Fax: 800-797-7406

 <http://www.sigmaplot.com> systatsoftware.com

Electronic Mail is not secure, may not be read every day, and should not be used for urgent or sensitive issues. 

 

email_logo

It’s OK to print this email.  Paper is a biodegradable, renewable, sustainable product made from trees.  Growing and harvesting trees provides jobs for millions of Americans.  Working forests are good for the environment and provide clean air and water, wildlife habitat and carbon storage.  Thanks to improved forest management, we have more trees in America today than we had one hundred years ago.

DISCLAIMER

The information transmitted is intended exclusively for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you are not the intended recipient or have received this mail in error, please notify the sender immediately and delete the material from your system.

**Comment by codemonkeynorth** [comment] 2017-08-13 18:51
@systatsoftware 
 
is it a debug email or is it an error email?

as far as i know you'll still get sent errors if debug is off

I think debug sends mail on both error *and* success
