### ISSUE TITLE
Compatibility with NinjaForms v3.0.29

### ISSUE THREAD

**Issue by Chugga** [zaus/forms-3rdparty-integration#81] opened 2017-02-26 08:21 UTC
I've been having some problems using this plugin with Ninja Forms v3.0.29. It doesn't seem to be firing at all. According to the [documentation](http://developer.ninjaforms.com/codex/custom-form-action/), the $ninja_forms_processing global has been removed. A brief reading of the code suggests that it relies on this variable, is that the case?

Otherwise is there some step I'm missing to ensure that the correct event fires?

I am running Wordpress v4.7.2 with NinjaForms v3.0.29 and Forms: 3rd Party Integration v1.7.1. I am also using the XML Post plugin, but it does not seem to fire at all either way.

Unfortunately I have not been able to get the plugin to produce logs/send emails.

**Comment by zaus** [comment] 2017-08-29 09:36
I was going to say it's not using that variable you mentioned -- it's [using the hook](https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/ninjaforms.php#L18) `ninja_forms_process` but then I did the obvious CTRL+F and [found it](https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/ninjaforms.php#L224).

I can't remember why I didn't use `ninja_forms_before_submission` or `ninja_forms_after_submission` instead (from [here](http://developer.ninjaforms.com/codex/submission-processing-hooks/)), but I'll have to look into it.

**Comment by zaus** [comment] 2017-08-29 09:37
Probably a dupe of #67

**Closed by zaus** 2017-08-29 09:37 UTC
Labels: bug, integration
